### ISSUE TITLE
 IMAP获取验证码失败怎么办

### ISSUE THREAD

**Issue by drdchm** [Yudaotor/Riot-Accounts-AutoChangePassword#10]
qq邮箱和163邮箱都试过，IMAP功能也开启了，最后都提示IMAP获取验证码失败

**Comment by Yudaotor** [comment]
授权码,不是邮箱密码

**Comment by drdchm** [comment]
是填的授权码啊，16位字母

**Comment by drdchm** [comment]
2023-07-19 10:48:32,928 ERROR: IMAP连接失败
2023-07-19 10:48:32,932 ERROR: Traceback (most recent call last):
  File "Handler.py", line 35, in IMAPHook
  File "imaplib2\imaplib2.py", line 2124, in __init__
  File "imaplib2\imaplib2.py", line 357, in __init__
  File "imaplib2\imaplib2.py", line 2136, in open
  File "imaplib2\imaplib2.py", line 473, in open_socket
  File "socket.py", line 826, in create_connection
  File "socket.py", line 961, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

2023-07-19 10:48:32,932 ERROR: IMAP获取验证码失败

**Comment by drdchm** [comment]
今天又用163的邮箱试，提示如上

**Comment by Yudaotor** [comment]
可能是网络问题？没有其他用户反应这个问题，都是可以正常使用的
