### ISSUE TITLE
求助报错闪退怎么办啊？

### ISSUE THREAD

**Issue by YoulQey** [Yudaotor/Riot-Accounts-AutoChangePassword#3]
配置文件：
![image](https://user-images.githubusercontent.com/53635729/229333408-cf395dad-6df3-4fb3-be26-be2f08bc67af.png)

日志显示：
2023-04-02 13:27:53,436 INFO: -------------------------------------------------
2023-04-02 13:27:53,436 INFO: ----------- Program started   ---------------
2023-04-02 13:27:53,436 INFO: ----------- 本项目开源于github   ---------------
2023-04-02 13:27:53,436 INFO: --------- 地址:https://github.com/Yudaotor/Riot-Accounts-AutoChangePassword ------------
2023-04-02 13:27:53,437 INFO: ----------- 可以点一个小星星吗(*^_^*) ---------------
2023-04-02 13:27:53,437 INFO: -------------------------------------------------
2023-04-02 13:27:53,440 ERROR: Traceback (most recent call last):
  File "main.py", line 28, in init
  File "Config.py", line 23, in __init__
ValueError: invalid literal for int() with base 10: ''

**Comment by Yudaotor** [comment]
不用邮箱的话就直接把那几行删除




三省
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yudaotor/Riot-Accounts-AutoChangePassword"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 中午1:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Yudaotor/Riot-Accounts-AutoChangePassword] 求助报错闪退怎么办啊？ (Issue #3)





 
配置文件：
 
 
日志显示：
 2023-04-02 13:27:53,436 INFO: -------------------------------------------------
 2023-04-02 13:27:53,436 INFO: ----------- Program started   ---------------
 2023-04-02 13:27:53,436 INFO: ----------- 本项目开源于github   ---------------
 2023-04-02 13:27:53,436 INFO: --------- 地址:https://github.com/Yudaotor/Riot-Accounts-AutoChangePassword ------------
 2023-04-02 13:27:53,437 INFO: ----------- 可以点一个小星星吗(^_^) ---------------
 2023-04-02 13:27:53,437 INFO: -------------------------------------------------
 2023-04-02 13:27:53,440 ERROR: Traceback (most recent call last):
 File "main.py", line 28, in init
 File "Config.py", line 23, in init
 ValueError: invalid literal for int() with base 10: ''

**Comment by YoulQey** [comment]
完美解决，超快的回复！
